### ISSUE TITLE
PayPro ToDo

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2674]
- [x] show paypro request information on click on the form (expiration time, etc)
- [x] show SSL certificate information
- [x] add refund address

**Comment by mikehearn** [comment]
Is supporting multiple outputs and different script types on the todo list too?

**Comment by matiu** [comment]
@mikehearn The original 3 point list is finished. Supporting multiple outputs and different script types is on the next iterations (just created https://github.com/bitpay/copay/issues/2830) . Do you have some examples of mechant / systems using those features on PayPro?

**Comment by mikehearn** [comment]
Nope. I doubt there are any merchants using it right now. It's indeed not a super high priority. I just want to make sure that when the day comes that people do want to use these things, they don't try and discover the features don't work.

**Comment by matiu** [comment]
Good point. Thanks!
