### ISSUE TITLE
WIP: New Backup  / Identity Roadmap

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3044]
- [x] support setting a new reqPubKey in BWS/BWC signed by xPrivKey (so reqPriv/PubKey can be regenerated from xPrivKey). The new reqPubKey need to be properly propagated to all Copayers.
 - [ ] support saving the encrypted walletPrivKey in BWS using a hash of the a xPrivKey derivation. So, walletPrivKey dont need to be persisted on a backup. Also, consider de case of changing BWS (wallet regeneration). (see case B) and C) in backup design document).
 - [x] support BIP39 at BWC / Credentials
 - [ ] new Identity class ... at BWC?
Still TODO.
